site_name: Olivier JACQUES's README
theme:
  name: material
  custom_dir: overrides
  favicon: favicon.ico
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.sections
    - navigation.top
site_url: https://www.olivierjacques.com/
repo_url: https://github.com/ojacques/ojacques.github.io
repo_name: ojacques.github.io.2

extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/ojacques2
    - icon: fontawesome/brands/github
      link: https://github.com/ojacques
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/olivierjacques/

nav:
  - README.md
  - Blog:
    - blog/index.md 

markdown_extensions:
  - mdx_truly_sane_lists:
      nested_indent: 2
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


